In [1]:
import numpy as np
import matplotlib.pyplot as plt

import tensorflow as tf
from tensorflow import GradientTape

In [2]:
x = tf.Variable(4.0)

with tf.GradientTape() as tape:
    y = x**2

In [3]:
y

<tf.Tensor: shape=(), dtype=float32, numpy=16.0>

In [4]:
dy_dx = tape.gradient(y, x)
dy_dx

<tf.Tensor: shape=(), dtype=float32, numpy=8.0>

In [5]:
w = tf.Variable(tf.random.normal((4, 2)))
w

<tf.Variable 'Variable:0' shape=(4, 2) dtype=float32, numpy=
array([[-0.17161866, -0.08234408],
       [-0.9092362 , -0.7766747 ],
       [-0.08874968, -0.97454506],
       [ 0.40851113,  0.40476117]], dtype=float32)>

In [6]:
b = tf.Variable(tf.ones(2, dtype=tf.float32))
b

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([1., 1.], dtype=float32)>

In [7]:
x = tf.Variable([[10., 20., 30.0, 40.0]], dtype=tf.float32)
x

<tf.Variable 'Variable:0' shape=(1, 4) dtype=float32, numpy=array([[10., 20., 30., 40.]], dtype=float32)>

In [8]:
with tf.GradientTape(persistent=True) as tape:
    y = tf.matmul(x, w) + b
    loss = tf.reduce_mean(y**2)

In [9]:
[dl_dw, dl_db] = tape.gradient(loss, [w, b])

In [10]:
dl_dw

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[  -52.229546,  -284.0284  ],
       [ -104.45909 ,  -568.0568  ],
       [ -156.68864 ,  -852.08527 ],
       [ -208.91818 , -1136.1136  ]], dtype=float32)>

In [11]:
dl_db

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ -5.2229548, -28.402842 ], dtype=float32)>

In [16]:
layer = tf.keras.layers.Dense(2, activation='relu')
x = tf.constant([[10., 20., 30.]])


In [17]:
with tf.GradientTape() as tape:
    y = layer(x)
    loss = tf.reduce_mean(y**2)

grad = tape.gradient(loss, layer.trainable_variables)

In [18]:
grad

[<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[177.3985,   0.    ],
        [354.797 ,   0.    ],
        [532.1955,   0.    ]], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([17.73985,  0.     ], dtype=float32)>]

In [19]:
x1 = tf.Variable(5.0)
x1

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=5.0>

In [20]:
x2 = tf.Variable(5.0, trainable=False)
x2

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=5.0>

In [22]:
x3 = tf.add(x1, x2)
x3

<tf.Tensor: shape=(), dtype=float32, numpy=10.0>

In [23]:
x4 = tf.constant(5.0)
x4

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

In [25]:
with tf.GradientTape() as tape:
    y = (x1**2) + (x2**2) + (x3**2) + (x4**2)

grad = tape.gradient(y, [x1, x2, x3, x4])
grad

[<tf.Tensor: shape=(), dtype=float32, numpy=10.0>, None, None, None]

In [26]:
x1 = tf.Variable(5.0)
x2 = tf.Variable(3.0)

with tf.GradientTape() as tape:
    tape.watch(x1)
    
    y = (x1**2) + (x2**2)

In [27]:
[dy_dx1, dy_dx2] = tape.gradient(y, [x1, x2])
dy_dx1, dy_dx2

(<tf.Tensor: shape=(), dtype=float32, numpy=10.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=6.0>)

In [28]:
with tf.GradientTape(watch_accessed_variables=False) as tape:
    tape.watch(x1)
    
    y = (x1**2) + (x2**2)

In [29]:
[dy_dx1, dy_dx2] = tape.gradient(y, [x1, x2])
dy_dx1, dy_dx2

(<tf.Tensor: shape=(), dtype=float32, numpy=10.0>, None)

In [30]:
x = tf.constant(1.0)
x1 = tf.Variable(5.0)
x2 = tf.Variable(3.0)

In [31]:
with tf.GradientTape(persistent=True) as tape:
    tape.watch(x)
    
    if x > 0.0:
        result = x1**2
    else:
        result = x2**2
     
dx1, dx2 = tape.gradient(result, [x1, x2])
dx1, dx2

(<tf.Tensor: shape=(), dtype=float32, numpy=10.0>, None)

In [32]:
x = tf.constant(-1.0)
x1 = tf.Variable(5.0)
x2 = tf.Variable(3.0)

In [33]:
with tf.GradientTape(persistent=True) as tape:
    tape.watch(x)
    
    if x > 0.0:
        result = x1**2
    else:
        result = x2**2
     
dx1, dx2 = tape.gradient(result, [x1, x2])
dx1, dx2

(None, <tf.Tensor: shape=(), dtype=float32, numpy=6.0>)

In [34]:
x = tf.Variable(2.)
y = tf.Variable(3.)

with tf.GradientTape() as tape:
    z = y * y
    
    dy_dx = tape.gradient(z, x)
    
print(dy_dx)

None
