In [1]:
import numpy as np
import matplotlib.pyplot as plt

import tensorflow as tf

In [2]:
x = tf.Variable(4.0)

with tf.GradientTape() as tape:
    y = x**2

In [3]:
y

<tf.Tensor: shape=(), dtype=float32, numpy=16.0>

In [4]:
dy_dx = tape.gradient(y, x)
dy_dx

<tf.Tensor: shape=(), dtype=float32, numpy=8.0>

In [5]:
w = tf.Variable(tf.random.normal((4, 2)))
w

<tf.Variable 'Variable:0' shape=(4, 2) dtype=float32, numpy=
array([[-0.17161866, -0.08234408],
       [-0.9092362 , -0.7766747 ],
       [-0.08874968, -0.97454506],
       [ 0.40851113,  0.40476117]], dtype=float32)>

In [6]:
b = tf.Variable(tf.ones(2, dtype=tf.float32))
b

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([1., 1.], dtype=float32)>

In [7]:
x = tf.Variable([[10., 20., 30.0, 40.0]], dtype=tf.float32)
x

<tf.Variable 'Variable:0' shape=(1, 4) dtype=float32, numpy=array([[10., 20., 30., 40.]], dtype=float32)>

In [8]:
with tf.GradientTape(persistent=True) as tape:
    y = tf.matmul(x, w) + b
    loss = tf.reduce_mean(y**2)

In [9]:
[dl_dw, dl_db] = tape.gradient(loss, [w, b])

In [10]:
dl_dw

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[  -52.229546,  -284.0284  ],
       [ -104.45909 ,  -568.0568  ],
       [ -156.68864 ,  -852.08527 ],
       [ -208.91818 , -1136.1136  ]], dtype=float32)>

In [11]:
dl_db

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ -5.2229548, -28.402842 ], dtype=float32)>

In [16]:
layer = tf.keras.layers.Dense(2, activation='relu')
x = tf.constant([[10., 20., 30.]])


In [17]:
with tf.GradientTape() as tape:
    y = layer(x)
    loss = tf.reduce_mean(y**2)

grad = tape.gradient(loss, layer.trainable_variables)

In [18]:
grad

[<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[177.3985,   0.    ],
        [354.797 ,   0.    ],
        [532.1955,   0.    ]], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([17.73985,  0.     ], dtype=float32)>]