In [4]:
import tensorflow as tf
import numpy as np

tf.debugging.set_log_device_placement(True)

In [5]:
tf.executing_eagerly()

True

In [7]:
x0 = tf.constant(3)
x0

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [8]:
print(x0)

tf.Tensor(3, shape=(), dtype=int32)


In [9]:
x0.shape

TensorShape([])

In [10]:
x0.dtype

tf.int32

In [11]:
x0.numpy()

np.int32(3)

In [13]:
result0 = x0 + 5
result0

Executing op AddV2 in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [14]:
x1 = tf.constant([1.1, 2.2, 3.3, 4.4])
x1

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1.1, 2.2, 3.3, 4.4], dtype=float32)>

In [16]:
result1 = x1 + 5
result1

Executing op AddV2 in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(4,), dtype=float32, numpy=array([6.1, 7.2, 8.3, 9.4], dtype=float32)>

In [18]:
result1 = x1 + tf.constant(5.0)
result1

Executing op AddV2 in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(4,), dtype=float32, numpy=array([6.1, 7.2, 8.3, 9.4], dtype=float32)>

In [20]:
result1 = tf.add(x1, tf.constant(5.0))
result1

Executing op AddV2 in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(4,), dtype=float32, numpy=array([6.1, 7.2, 8.3, 9.4], dtype=float32)>

In [22]:
x2 = tf.constant([[1, 2, 3, 4], [5, 6, 7, 8]])
x2

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int32)>

In [23]:
x2 = tf.cast(x2, tf.float32)
x2

Executing op Cast in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]], dtype=float32)>

In [24]:
x1

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1.1, 2.2, 3.3, 4.4], dtype=float32)>

In [25]:
arr_x1 = x1.numpy()
arr_x1

array([1.1, 2.2, 3.3, 4.4], dtype=float32)

In [27]:
arr_x4 = np.array([[10, 20], [30, 40], [50, 60]])
arr_x4

array([[10, 20],
       [30, 40],
       [50, 60]])

In [28]:
x4 = tf.convert_to_tensor(arr_x4)
x4

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[10, 20],
       [30, 40],
       [50, 60]])>

In [29]:
np.square(x2)

array([[ 1.,  4.,  9., 16.],
       [25., 36., 49., 64.]], dtype=float32)

In [30]:
np.sqrt(x2)

array([[1.       , 1.4142135, 1.7320508, 2.       ],
       [2.236068 , 2.4494898, 2.6457512, 2.828427 ]], dtype=float32)

In [31]:
tf.is_tensor(arr_x4)

False

In [32]:
tf.is_tensor(x4)

True

In [33]:
t0 = tf.zeros([3, 5], tf.int32)
t0

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Fill in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)>

In [34]:
t1 = tf.ones([2, 3], tf.int32)
t1

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Fill in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)>

In [35]:
t0_reshaped = tf.reshape(t0, [5, 3])
t0_reshaped

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Reshape in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(5, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)>

In [36]:
v1 = tf.Variable([[1.5, 2, 5], [2, 6, 8]])
v1

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1.5, 2. , 5. ],
       [2. , 6. , 8. ]], dtype=float32)>

In [37]:
v2 = tf.Variable([[1, 2, 3], [4, 5, 6]])
v2

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [38]:
v2 = tf.Variable([[1, 2, 3], [4, 5, 6]], dtype=tf.float32)
v2

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [39]:
tf.add(v1, v2)

Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AddV2 in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 2.5,  4. ,  8. ],
       [ 6. , 11. , 14. ]], dtype=float32)>

In [40]:
tf.convert_to_tensor(v1)

Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1.5, 2. , 5. ],
       [2. , 6. , 8. ]], dtype=float32)>

In [41]:
v1.numpy()

Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


array([[1.5, 2. , 5. ],
       [2. , 6. , 8. ]], dtype=float32)

In [42]:
v1

Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1.5, 2. , 5. ],
       [2. , 6. , 8. ]], dtype=float32)>

In [43]:
v1.assign([[10, 20, 30], [40, 50, 60]])
v1

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[10., 20., 30.],
       [40., 50., 60.]], dtype=float32)>

In [44]:
v1[0, 0].assign(100)
v1

Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op StridedSlice in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ResourceStridedSliceAssign in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[100.,  20.,  30.],
       [ 40.,  50.,  60.]], dtype=float32)>

In [45]:
v1.assign_add([[1,1,1], [1,1,1]])
v1

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignAddVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[101.,  21.,  31.],
       [ 41.,  51.,  61.]], dtype=float32)>

In [46]:
v1.assign_sub([[2,2,2], [2,2,2]])
v1

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignSubVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[99., 19., 29.],
       [39., 49., 59.]], dtype=float32)>

In [47]:
var_a = tf.Variable([2.0, 3.0])
var_a

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([2., 3.], dtype=float32)>

In [48]:
var_b = tf.Variable(var_a)
var_b

Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([2., 3.], dtype=float32)>

In [49]:
var_b.assign([200, 300])
var_b

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([200., 300.], dtype=float32)>

In [50]:
var_a

Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([2., 3.], dtype=float32)>

In [51]:
print(var_a.numpy())
print(var_b.numpy())

Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0
[2. 3.]
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0
[200. 300.]
