In [1]:
import time
import warnings
import logging
import tensorflow as tf

In [2]:
@tf.function
def add(a, b):
    return a + b

@tf.function
def sub(a, b):
    return a - b

@tf.function
def mul(a, b):
    return a * b

@tf.function
def div(a, b):
    return a / b

In [3]:
print(add(tf.constant(5), tf.constant(2)))

tf.Tensor(7, shape=(), dtype=int32)


In [4]:
print(sub(tf.constant(5), tf.constant(2)))

tf.Tensor(3, shape=(), dtype=int32)


In [5]:
print(mul(tf.constant(5), tf.constant(2)))

tf.Tensor(10, shape=(), dtype=int32)


In [6]:
print(div(tf.constant(5), tf.constant(2)))

tf.Tensor(2.5, shape=(), dtype=float64)


In [8]:
@tf.function
def matmul(a, b):
    return tf.matmul(a, b)

In [13]:
@tf.function
def linear(m, x, c):
    return add(matmul(m, x), c)

In [9]:
m = tf.constant([[4.0, 5.0, 6.0]], tf.float32)
m

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[4., 5., 6.]], dtype=float32)>

In [10]:
x = tf.Variable([[100.0], [100.0], [100.0]], tf.float32)
x

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[100.],
       [100.],
       [100.]], dtype=float32)>

In [11]:
c = tf.constant([[1.0]], tf.float32)
c

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[1.]], dtype=float32)>

In [14]:
linear(m, x, c)

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[1501.]], dtype=float32)>

In [15]:
@tf.function
def pos_neg_check(x):
    reduce_sum = tf.reduce_sum(x)
    
    if reduce_sum > 0:
        return tf.constant(1)

    elif reduce_sum == 0:
        return tf.constant(0)
    
    else:
        return tf.constant(-1)

In [16]:
pos_neg_check(tf.constant([100, 100]))

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [17]:
pos_neg_check(tf.constant([100, -100]))

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [18]:
pos_neg_check(tf.constant([-100, -100]))

<tf.Tensor: shape=(), dtype=int32, numpy=-1>

In [23]:
num = tf.Variable(7)

In [24]:
@tf.function
def add_times(x):
    for i in tf.range(x):
        num.assign_add(x)

In [25]:
add_times(5)

In [26]:
print(num)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=32>


In [28]:
a = tf.Variable(1.0)
b = tf.Variable(2.0)

In [29]:
@tf.function
def f(x, y):
    a.assign(y * b)
    b.assign_add(x * a)
    return a + b

In [30]:
f(1, 2)

<tf.Tensor: shape=(), dtype=float32, numpy=10.0>

In [31]:
@tf.function
def square(a):
    print("Input a: ", a)
    return a * a

In [32]:
x = tf.Variable([[2, 2], [2, 2]], dtype=tf.float32)
square(x)

Input a:  <tf.Variable 'Variable:0' shape=(2, 2) dtype=float32>


<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[4., 4.],
       [4., 4.]], dtype=float32)>

In [33]:
y = tf.Variable([[2, 2], [2, 2]], dtype=tf.int32)
square(y)

Input a:  <tf.Variable 'Variable:0' shape=(2, 2) dtype=int32>


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 4],
       [4, 4]], dtype=int32)>

In [34]:
z = tf.Variable([[3, 3], [3, 3]], dtype=tf.float32)
square(z)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[9., 9.],
       [9., 9.]], dtype=float32)>

In [35]:
concrete_int_square_fn = square.get_concrete_function(tf.TensorSpec(shape=None, dtype=tf.int32))
concrete_int_square_fn

Input a:  Tensor("a:0", dtype=int32)


<ConcreteFunction (a: TensorSpec(shape=<unknown>, dtype=tf.int32, name=None)) -> TensorSpec(shape=<unknown>, dtype=tf.int32, name=None) at 0x1968C763320>

In [36]:
concrete_float_square_fn = square.get_concrete_function(tf.TensorSpec(shape=None, dtype=tf.float32))
concrete_float_square_fn

Input a:  Tensor("a:0", dtype=float32)


<ConcreteFunction (a: TensorSpec(shape=<unknown>, dtype=tf.float32, name=None)) -> TensorSpec(shape=<unknown>, dtype=tf.float32, name=None) at 0x1968C6BF6B0>

In [37]:
concrete_int_square_fn(tf.constant([[2, 2], [2, 2]], dtype=tf.int32))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 4],
       [4, 4]], dtype=int32)>

In [38]:
concrete_float_square_fn(tf.constant([[2.1, 2.1], [2.1, 2.1]], dtype=tf.float32))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[4.4099994, 4.4099994],
       [4.4099994, 4.4099994]], dtype=float32)>

In [39]:
concrete_float_square_fn(tf.constant([[2, 2], [2, 2]], dtype=tf.int32))

InvalidArgumentError: cannot compute __inference_square_416 as input #0(zero-based) was expected to be a float tensor but is a int32 tensor [Op:__inference_square_416]

In [40]:
@tf.function
def f(x):
    print("Python execution: ", x)
    tf.print("Graph execution: ", x)

In [41]:
f(1)

Python execution:  1
Graph execution:  1


In [42]:
f(1)

Graph execution:  1


In [43]:
f("Hello tf.function!")

Python execution:  Hello tf.function!
Graph execution:  Hello tf.function!
